[project]
name = "helloworld"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rahaf", email = "rahafalkiuymi.saeed@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
helloworld = "helloworld:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
